### ISSUE TITLE
options object in readme is unclear

### ISSUE THREAD

**Issue by ryan-schroeder** [strongloop/loopback-example-ssl#23]
Thanks for this example!  The "options" object in the readme confused me: I thought it was the "options" object to be passed to the "boot" method (the first result when you search the docs for "options").

Not a huge deal, but as a beginner to loopback, it took me a good half-hour to look at differences between your files and mine and figure out my mistake.

**Comment by dhmlau** [comment]
@ryan-schroeder, thanks for your interest in LoopBack.  Would you like to submit a PR to improve the `README.md`?
